#!/usr/bin/python
# -*- coding: utf-8 -*-
########################################################################################
#
# Copyright by Stefan Koch <StefanKoch@gmx.org>, 2015
#
# This file is part of omxAutomation
#
#    omxAutomation is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    omxAutomation is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with Foobar.  If not, see <http://www.gnu.org/licenses/>.
#
########################################################################################

import cgi, cgitb 
import urllib
import os

#######################################################################################
#Defines you need to adapt
base             = '/mnt/video/'

#######################################################################################
print "Content-Type: text/html"
print

## get data from CGI
form = cgi.FieldStorage() 

# Get data from fields
chdir   = form.getvalue('chdir')
lastpwd = form.getvalue('pwd')
play    = form.getvalue('play')

## set all variables to expected values
if (chdir == None):
	chdir = ''

if (lastpwd == None):
	lastpwd = ''

if (play == None):
	play = ''

if (chdir == "Unbekannt"):
	chdir = ''

if (lastpwd == "Unbekannt"):
	lastpwd = ''

#######################################################################################
#simple html encoder
html_escape_table = {
    "ä": "&auml;",
    "ü": "&uuml;",
    "ö": "&ouml;",
}

def html_encode(text):
    return "".join(html_escape_table.get(c,c) for c in text)

#######################################################################################
## render page
print '''
<!DOCTYPE html>
<html>
<head>
<title>Raspberry Video List</title>
<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0\">
<meta name=\"mobile-web-app-capable\" content=\"yes\">
<style type=\"text/css\">
BODY
   {
   color:#3EF700;
   background-color:black;
   font-family:sans-serif;
   font-size: 150%;
   }
A:link{
	color:white;
	text-decoration:none;
}
A:visited{
	color:white;
	text-decoration:none;
}
div {
    background-color: #333333;
    padding: 20px 0px 20px 10px;
}
#dir {
    background-color: #222255;
}
</style>
</head>
<body>
<h2>Raspberry Video List</h2>
'''

## this is the page entry enumerator
idx=1

## handle chdir request
workpwd = lastpwd
if (chdir != ''):
	if ((chdir == '__go_up__')):
		## we dont allow .. but instead __go_up__ is told
		## FIXME actually check for .. and filter out...
		workpwd += "/../"
	else:
		## normal decend into subdir
		workpwd += '/' + chdir

## cleanup paths
workpwd = os.path.normpath(workpwd) 
workdir = os.path.normpath(base + '/' + workpwd)

#####################################################################################
## header
print('<div id=dir>')
print('<a href=\"/cgi-bin/vidplay\">[Player]</a>'+ 
	'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;')

if (workpwd != '.'):
	print('<a href=\"/cgi-bin/vidlist\">[Home]</a>'+
	'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;' +
	'<a href=\"/cgi-bin/vidlist?'+
	'chdir=' + urllib.quote('__go_up__', '')+'&'+
	'pwd=' + urllib.quote(workpwd, '') + "\">[" + html_encode("Zurück") + "]</a>")

print('</div><br>')

#####################################################################################
## traverse directory and list items
dirlist = os.listdir(workdir)

for e in dirlist:
	## ------------ now we display a directory entry ---------------------------
	if (os.path.isdir(workdir + '/' + e)):
		print('<div id=dir><a href=\"/cgi-bin/vidlist?'+
			'chdir=' + urllib.quote(e, '')+'&'+
			'pwd=' + urllib.quote(workpwd, '')+
			'\">'+ str(idx)+ ' : '+ html_encode(e) +'</a></div><br>')

	## ------------ now we display a file entry ---------------------------
	if (os.path.isfile(workdir + '/' + e)):
		print("<div><a href=\"/cgi-bin/vidplay?"+
			"op=play&" +
			"play=" + urllib.quote(e, '') + "&" +
			"pwd="  + urllib.quote(workpwd, '') +
			"\">"+ str(idx)+ ' : ' + html_encode(e) + '</a></div><br>' )
	idx += 1

print '''
</body>
</html>
'''

