#!/usr/bin/python
########################################################################################
#
# Copyright by Stefan Koch <StefanKoch@gmx.org>, 2015
#
# This file is part of omxAutomation
#
#    omxAutomation is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    omxAutomation is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with Foobar.  If not, see <http://www.gnu.org/licenses/>.
#
########################################################################################

import cgi, cgitb 
import paho.mqtt.client as mqtt
import os
import urllib

########################################################################################
#Defines you need to adapt
install_path     = "/home/stefan/bin"
base             = '/mnt/video/'
mqtt_broker_ip   = "192.168.2.100"
mqtt_broker_port = "1883"
mqtt_omx_topic   = "/omxserver/play"

########################################################################################
print "Content-Type: text/html"
print ""

## Get CGI Data
form = cgi.FieldStorage() 

# Get data from fields
op      = form.getvalue('op')
playurl = form.getvalue('play')
playpwd = form.getvalue('pwd')

## we dont want uninitialized data
if (playurl == None):
	playurl="Unbekannt"
if (playpwd == None):
	playpwd="Unbekannt"

## url is the full/absolute file path of the video
url = os.path.normpath(base + "/" + playpwd + "/" + playurl)

## transfer request to omxserver
def send(op):
	if (op == "play"):
		mqttc.publish(mqtt_omx_topic, "play," + base + "/" + playpwd + "/" + playurl)
		return
	if (op == "back"):
		mqttc.publish(mqtt_omx_topic, "back,0")
		return
	if (op == "fwd"):
		mqttc.publish(mqtt_omx_topic, "fwd,0")
		return
	if (op == "playpause"):
		mqttc.publish(mqtt_omx_topic, "playpause,0")
		return
	if (op == "quit"):
		mqttc.publish(mqtt_omx_topic, "quit,0")
		return

if (op == None):
	op="not set"
else:
	## this is done always at first step - get connection to broker
	mqttc = mqtt.Client()
	mqttc.connect(mqtt_broker_ip, mqtt_broker_port)
	if (op == "list"):
		listmovies()
	else:
		send(op)
	mqttc.loop(2)

##############################################################################
# actual page to render
print '''
<!DOCTYPE html>
<html>
<head>
<title>Raspberry Video Player</title>
<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0\">
<style type=\"text/css\">
BODY
   {
   color:#3EF700;
   background-color:black;
   font-family:sans-serif;
   }
A:link{color:black}
A:visited{color:black}
.cmdBut {
  background: #34d95d;
  background-image: -webkit-linear-gradient(top, #34d95d, #2bb82b);
  background-image: -moz-linear-gradient(top, #34d95d, #2bb82b);
  background-image: -ms-linear-gradient(top, #34d95d, #2bb82b);
  background-image: -o-linear-gradient(top, #34d95d, #2bb82b);
  background-image: linear-gradient(to bottom, #34d95d, #2bb82b);
  -webkit-border-radius: 9;
  -moz-border-radius: 9;
  border-radius: 9px;
  font-family: Arial;
  color: #000000;
  font-size: 20px;
  padding: 20px 40px 20px 40px;
  text-decoration: none;
}
.cmdBut:hover {
  background: #8cff00;
  text-decoration: none;
}
</style>
</head>
<body>
<h2>Raspberry Video Control</h2>'''

## display the current file to play
print(playurl + "<br><br><br>")

## command buttons
print("<a href=\"/cgi-bin/vidplay?op=back&" +
	"play=" + urllib.quote(playurl, '') + "&" +
	"pwd="  + urllib.quote(playpwd, '') +
	"\" class=cmdBut>&lt;&lt;</a>")

print("<a href=\"/cgi-bin/vidplay?op=playpause&" +
	"play=" + urllib.quote(playurl, '') + "&" +
	"pwd="  + urllib.quote(playpwd, '') +
	"\" class=cmdBut>II&gt;&gt;</a>")

print("<a href=\"/cgi-bin/vidplay?op=fwd&" +
	"play=" + urllib.quote(playurl, '') + "&" +
	"pwd="  + urllib.quote(playpwd, '') + 
	"\" class=cmdBut>&gt;&gt;</a><br><br><br><br>")

print("<a href=\"/cgi-bin/vidplay?op=quit&" + 
	"play=" + urllib.quote(playurl, '') + "&" +
	"pwd="  + urllib.quote(playpwd, '') +
	"\" class=cmdBut>Video beenden</a><br><br><br><br>")

print("<a href=\"/cgi-bin/vidlist?pwd=.&" + 
	"chdir=" + urllib.quote(playpwd, '') + 
	"\" class=cmdBut>Liste Filme</a><br><br><br><br>")

print '''
</body>
</html>
'''

